# Generated by Django 4.2 on 2023-04-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DCompetencyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Код компетенции',
                'verbose_name_plural': 'Коды компетенции',
            },
        ),
        migrations.CreateModel(
            name='DControlType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DEdIzmereniya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Поколение',
                'verbose_name_plural': 'Поколения',
            },
        ),
        migrations.CreateModel(
            name='DModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DSpecialozationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип специализации',
                'verbose_name_plural': 'Типы специализаций',
            },
        ),
        migrations.CreateModel(
            name='DTypeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DTypeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Стандарт',
                'verbose_name_plural': 'Стандарты',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name_group', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=8)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SprBranch',
            fields=[
                ('id_branch', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('d_competency_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dcompetencycode')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='SprCompulsoryDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'verbose_name': 'Обязательная дисциплина',
                'verbose_name_plural': 'Обязательные дисциплины',
            },
        ),
        migrations.CreateModel(
            name='SprDegreeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_deg', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprFaculty',
            fields=[
                ('id_faculty', models.AutoField(primary_key=True, serialize=False)),
                ('name_faculty', models.CharField(max_length=255)),
                ('dean', models.CharField(max_length=255)),
                ('id_branch', models.ForeignKey(db_column='id_branch', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprbranch')),
            ],
        ),
        migrations.CreateModel(
            name='SprFormEducation',
            fields=[
                ('id_form', models.AutoField(primary_key=True, serialize=False)),
                ('form', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprNameOp',
            fields=[
                ('id_spec', models.AutoField(primary_key=True, serialize=False)),
                ('num_profile', models.CharField(max_length=255)),
                ('name_spec', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprOkco',
            fields=[
                ('program_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name_okco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprRop',
            fields=[
                ('id_rop', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SprStandardZet',
            fields=[
                ('id_standard', models.AutoField(primary_key=True, serialize=False)),
                ('type_standard', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TblRealizedOkso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprokco')),
                ('spr_branch', models.ForeignKey(db_column='spr_branch_id_branch', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprbranch')),
            ],
            options={
                'verbose_name': 'Реализуемый ОКСО',
                'verbose_name_plural': 'Реализуемые ОКСО',
            },
        ),
        migrations.CreateModel(
            name='TblAup',
            fields=[
                ('id_aup', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255)),
                ('num_aup', models.CharField(max_length=255)),
                ('base', models.CharField(max_length=255)),
                ('type_educ', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('type_standard', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('period_educ', models.CharField(max_length=255)),
                ('years', models.IntegerField()),
                ('months', models.IntegerField(blank=True, null=True)),
                ('year_beg', models.IntegerField()),
                ('year_end', models.IntegerField()),
                ('is_actual', models.IntegerField()),
                ('zet', models.IntegerField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('id_degree', models.ForeignKey(db_column='id_degree', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprdegreeeducation')),
                ('id_faculty', models.ForeignKey(db_column='id_faculty', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprfaculty')),
                ('id_form', models.ForeignKey(db_column='id_form', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprformeducation')),
                ('id_rop', models.ForeignKey(db_column='id_rop', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprrop')),
                ('id_spec', models.ForeignKey(db_column='id_spec', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprnameop')),
            ],
        ),
        migrations.CreateModel(
            name='SprVolumeDegreeZet',
            fields=[
                ('id_volume_deg', models.AutoField(primary_key=True, serialize=False)),
                ('id_standard', models.IntegerField()),
                ('program_code', models.ForeignKey(db_column='program_code', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprokco')),
            ],
        ),
        migrations.CreateModel(
            name='SprSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('d_specialozation_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dspecialozationtype')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализации',
            },
        ),
        migrations.AddField(
            model_name='sprnameop',
            name='program_code',
            field=models.ForeignKey(db_column='program_code', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.sprokco'),
        ),
        migrations.CreateModel(
            name='SprFgosVo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', default=False, null=True, verbose_name='Активно')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('approval_date', models.DateField(verbose_name='Дата утверждения')),
                ('modification_date', models.DateField(verbose_name='Дата изменения')),
                ('active_from', models.DateField(verbose_name='Вступает в силу с')),
                ('competencies', models.ManyToManyField(to='backend.sprcompetency', verbose_name='Компетенции')),
                ('compulsory_disciplines', models.ManyToManyField(to='backend.sprcompulsorydiscipline', verbose_name='Обязательные дисциплины')),
                ('generation', models.ForeignKey(db_column='d_generation_id', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dgeneration', verbose_name='Стандарт')),
                ('specialozations', models.ManyToManyField(blank=True, null=True, to='backend.sprspecialization', verbose_name='Специализации')),
                ('tbl_realized_okso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tblrealizedokso', verbose_name='Реализуемый ОКСО')),
                ('type_standard', models.ForeignKey(db_column='d_type_standard_id', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dtypestandard', verbose_name='Стандарт')),
            ],
            options={
                'verbose_name': 'ФГОС ВО',
                'verbose_name_plural': 'ФГОС ВО',
            },
        ),
        migrations.CreateModel(
            name='AupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifr', models.CharField(max_length=30)),
                ('id_group', models.IntegerField()),
                ('discipline', models.CharField(max_length=150)),
                ('id_period', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('zet', models.IntegerField()),
                ('num_row', models.IntegerField()),
                ('id_aup', models.ForeignKey(db_column='id_aup', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.tblaup')),
                ('id_block', models.ForeignKey(db_column='id_block', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dblocks')),
                ('id_edizm', models.ForeignKey(db_column='id_edizm', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dedizmereniya')),
                ('id_module', models.ForeignKey(db_column='id_module', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dmodules')),
                ('id_part', models.ForeignKey(db_column='id_part', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dpart')),
                ('id_type_control', models.ForeignKey(db_column='id_type_control', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dcontroltype')),
                ('id_type_record', models.ForeignKey(db_column='id_type_record', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.dtyperecord')),
            ],
        ),
    ]
