# Generated by Django 4.2 on 2023-04-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprfgosvo',
            name='specialozations',
            field=models.ManyToManyField(blank=True, to='backend.sprspecialization', verbose_name='Специализации'),
        ),
    ]
