# Generated by Django 4.2 on 2023-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_sprfgosvo_specialozations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprcompetency',
            name='title',
            field=models.TextField(),
        ),
    ]
