# Generated by Django 4.2 on 2023-04-24 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_sprspecialization_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprAdditionalCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(max_length=2)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.dcompetencycode')),
            ],
        ),
        migrations.AddField(
            model_name='sprspecialization',
            name='additional_competencies',
            field=models.ManyToManyField(to='backend.spradditionalcompetency', verbose_name='Дополнительные компетенции'),
        ),
    ]
